#lang racket

;; Slog configuration loader (docs: config/Config.md).
;;
;; Settings are a dogfooded Slog program: config/config.slog (or, if absent, the
;; tracked config/default-config.slog) derives a settings database from the
;; system facts the front end injects (config/system.slog).  We run that program
;; ONCE via the normal pipeline, cache the resulting CSVs under
;; config/cache/<hash>/, and thereafter just read the cache (no compile, no
;; daemon) unless the config files or the detected system change.
;;
;; The computed settings are applied by populating the SLOG_* environment
;; variables the rest of the toolchain already reads -- so nothing downstream
;; needs to know about the config system, and an SLOG_* the user set explicitly
;; is NEVER overwritten (precedence: CLI/env > config > code default).

(provide load-config!)

(require racket/runtime-path
         racket/future           ; processor-count
         racket/random)          ; crypto-random-bytes
(require sha)

(define-runtime-path config-dir "../config")
(define-runtime-path slog-main "../slog.rkt")

;; Bump to invalidate every cache when the settings schema / env mapping changes.
(define SCHEMA-VERSION "3")

;; setting name -> the env var the toolchain already consults for it.
(define setting->env
  (hash "threads"     "SLOG_THREADS"
        "build_jobs"  "SLOG_BUILD_JOBS"
        "opt"         "SLOG_OPT"
        ;; tiered compilation: seconds before an in-flight background -O2 build's
        ;; claim marker is presumed abandoned by a dead builder (docs/fast-compile.md §13)
        "o2_reclaim_secs" "SLOG_O2_RECLAIM_SECS"
        ;; build/o content-addressed .o cache GC (docs/fast-compile.md §14):
        ;; evict entries unused longer than N days, and keep the cache under a
        ;; byte cap (evicting oldest first)
        "o_cache_max_age_days" "SLOG_O_CACHE_MAX_AGE_DAYS"
        "o_cache_max_mb"       "SLOG_O_CACHE_MAX_MB"
        "max_ms"      "SLOG_MAX_MS"
        "slice_ms"    "SLOG_SLICE_MS"
        "mem_max"     "SLOG_MEM_MAX"
        "mem_bytes"   "SLOG_MEM_BYTES"
        ;; external SMT oracle (docs/smt.md): the solver chain
        ;; ("z3:500,cvc5:2000" | "mock") and the worker-pool size
        "smt_solvers" "SLOG_SMT_SOLVERS"
        "oracle_procs" "SLOG_ORACLE_PROCS"
        ;; bignum caps (docs/primitives.md §14.4): per-value bit cap and the
        ;; whole-table approximate byte cap
        "mpz_max_bits"    "SLOG_MPZ_MAX_BITS"
        "mpz_table_bytes" "SLOG_MPZ_TABLE_BYTES"))

;; ---- entry point --------------------------------------------------------
;; Called once, early, from slog.rkt.  Best-effort: any failure falls back to
;; the built-in code defaults (which are themselves dynamic, e.g. cores-1).
(define (load-config!)
  (when (config-enabled?)
    (with-handlers ([exn:fail?
                     (λ (e)
                       (eprintf "warning: slog config load failed (~a); using built-in defaults\n"
                                (exn-message e)))])
      (do-load-config!))))

(define (env-set? v) (let ([x (getenv v)]) (and x (not (string=? x "")))))

(define (config-enabled?)
  (and (not (getenv "SLOG_CONFIG_BOOTSTRAP"))  ; we ARE the config run -> no recursion
       (not (env-set? "SLOG_NO_CONFIG"))))     ; explicit opt-out

(define (active-config-file)
  (define user (build-path config-dir "config.slog"))
  (define def  (build-path config-dir "default-config.slog"))
  (cond [(file-exists? user) user]
        [(file-exists? def)  def]
        [else #f]))

(define (do-load-config!)
  (define cfg (active-config-file))
  (when cfg
    (write-system-facts!)
    (define hash (config-hash cfg))
    (define cache-root (build-path config-dir "cache"))
    (define cache-dir  (build-path cache-root hash))
    (make-directory* cache-root)
    (unless (settings-cached? cache-dir)
      (build-config-cache! cfg cache-dir))
    (apply-settings! (read-settings cache-dir))))

;; ---- system detection ---------------------------------------------------
(define (detect-ram-mb)
  (with-handlers ([exn:fail? (λ (_) #f)])
    (and (file-exists? "/proc/meminfo")
         (for/or ([line (in-list (file->lines "/proc/meminfo"))])
           (define m (regexp-match #rx"^MemTotal:[ ]+([0-9]+) kB" line))
           (and m (quotient (string->number (second m)) 1024))))))

(define (write-system-facts!)
  (define cores (processor-count))
  (define ram   (or (detect-ram-mb) 0))
  (define content
    (string-append
     ";; GENERATED by compiler/config.rkt each run -- do not edit.\n"
     ";; Detected system facts, included by config/default-config.slog.\n"
     "table (sys_cores int)\n"
     "table (sys_ram_mb int)\n"
     "rule\n"
     (format "(sys_cores ~a)\n" cores)
     (format "(sys_ram_mb ~a)\n" ram)))
  (define f (build-path config-dir "system.slog"))
  ;; Idempotent + atomic: only rewrite when the content actually changed, and via
  ;; a temp+rename, so concurrent `slog` invocations (run-tests.sh -jN) neither
  ;; race-truncate the file nor cause a torn read during config hashing (a warm
  ;; cache then stays a pure read).
  (unless (and (file-exists? f) (string=? (file->string f) content))
    (define tmp (build-path config-dir
                            (string-append "system.slog."
                                           (bytes->hex-string (crypto-random-bytes 6)) ".tmp")))
    (call-with-output-file tmp #:exists 'replace (λ (o) (write-string content o)))
    (rename-file-or-directory tmp f #t)))

;; ---- cache keying -------------------------------------------------------
;; Hash the schema version + the config files + the detected system facts, so a
;; changed config OR a different machine (core/RAM count) recomputes.
(define (config-hash cfg)
  (define deff (build-path config-dir "default-config.slog"))
  (define sysf (build-path config-dir "system.slog"))
  (define input
    (string-append SCHEMA-VERSION "\n"
                   (file->string cfg) "\n"
                   (if (file-exists? deff) (file->string deff) "") "\n"
                   (file->string sysf)))
  (bytes->hex-string (sha256 (string->bytes/utf-8 input))))

;; The cache dir is published by an atomic rename that only happens once the
;; settings were fully produced, so its mere existence means "valid".
(define (settings-cached? dir) (directory-exists? dir))

(define (has-settings? dir)
  (ormap (λ (n) (file-exists? (build-path dir n)))
         '("setting_int.csv" "setting_str.csv" "override_int.csv" "override_str.csv")))

;; ---- run the config program (cache miss) --------------------------------
;; Runs via a fresh `racket slog.rkt` subprocess with SLOG_CONFIG_BOOTSTRAP set
;; (so its own load-config! is a no-op).  Writes into a temp dir, then atomically
;; renames it into place -- so a crash or a concurrent build never leaves a
;; half-written cache that settings-cached? would trust.
(define (build-config-cache! cfg cache-dir)
  (define tmp (build-path (path-only cache-dir)
                          (string-append (path->string (file-name-from-path cache-dir))
                                         ".building")))
  (when (directory-exists? tmp) (delete-directory/files tmp))
  (make-directory* tmp)
  (define racket-exe
    (or (let ([e (find-system-path 'exec-file)]) (and e (find-executable-path e)))
        (find-executable-path "racket")
        "racket"))
  (define child-env (environment-variables-copy (current-environment-variables)))
  (environment-variables-set! child-env #"SLOG_CONFIG_BOOTSTRAP" #"1")
  (define code
    (parameterize ([current-environment-variables child-env])
      (define-values (sp out in err)
        (subprocess #f #f (current-error-port)
                    racket-exe (path->string slog-main)
                    "--no-banner" "--debug-dir" (path->string tmp)
                    (path->string cfg)))
      (close-output-port in)
      (copy-port out (open-output-nowhere))   ; drain the daemon's (fixpoint ...) chatter
      (close-input-port out)
      (subprocess-wait sp)
      (subprocess-status sp)))
  (cond
    [(has-settings? tmp)
     (if (directory-exists? cache-dir)
         (delete-directory/files tmp)                 ; lost a race; keep the winner
         (rename-file-or-directory tmp cache-dir #t))]
    [else
     (delete-directory/files tmp #:must-exist? #f)
     (error (format "config program produced no settings (exit ~a)" code))]))

;; ---- read + apply -------------------------------------------------------
;; CSV columns are space-separated; strings are "quoted".  Setting names and
;; string values contain no spaces (enforced by convention, see default-config).
(define (unquote-str s)
  (define n (string-length s))
  (if (and (>= n 2) (char=? (string-ref s 0) #\") (char=? (string-ref s (sub1 n)) #\"))
      (substring s 1 (sub1 n))
      s))

(define (read-settings dir)
  (define h (make-hash))
  (define (load-file name value-quoted?)
    (define f (build-path dir name))
    (when (file-exists? f)
      (for ([line (in-list (file->lines f))])
        (define cols (string-split line))                 ; splits on any whitespace run
        (when (>= (length cols) 2)
          (hash-set! h (unquote-str (first cols))
                     (if value-quoted? (unquote-str (second cols)) (second cols)))))))
  (load-file "setting_int.csv" #f)     ; defaults first ...
  (load-file "setting_str.csv" #t)
  (load-file "override_int.csv" #f)    ; ... then overrides win (later hash-set!)
  (load-file "override_str.csv" #t)
  h)

;; Populate the SLOG_* env for each known setting, never clobbering a value the
;; user already set (that is the override channel).
(define (apply-settings! settings)
  (for ([(name env) (in-hash setting->env)])
    (define v (hash-ref settings name #f))
    (when (and v (not (env-set? env)))
      (putenv env v))))
