#lang racket

;; Reify a Slog program as Slog facts, for analyses of Slog written in Slog
;; (analysis/slog-lint.slog).  The program is read by the compiler's own
;; parser, its includes resolved as modules.rkt resolves them, and each
;; declaration, rule, clause and term becomes a fact over the schema in
;; analysis/schema.slog.  Nothing is desugared: the facts describe the
;; program as written, every atom and variable at its line and column.
;;
;;   racket compiler/reify.rkt FILE                 the facts as a Slog program
;;   racket compiler/reify.rkt --freeze NAME FILE   ... as the database data/NAME
;;   racket compiler/reify.rkt --serve              one JSON request a line:
;;     {"id": 1, "path": "/abs/main.slog", "sources": {...}, "freeze": "NAME", "program": "/abs/facts.slog"}
;;   answered with {"id", "ok", "ms", "facts", "error"?}.
;;
;; A database is how an analysis reads the facts quickly: `open NAME`, then
;; `run analysis/slog-lint.slog` compiles only the analysis, and that
;; compilation is cached; a program including the facts would compile them
;; too, on every edit.  `sources` are unsaved texts read in place of the
;; files they name, as in compiler/check.rkt.  Run from the repository root,
;; where data/ and daemon/slog-freeze (built on first use) are.

(require json
         racket/runtime-path
         "parser.rkt"
         "lexer.rkt"
         (only-in "modules.rkt" resolve-include)
         (only-in "primitives.rkt" prim-fun-env)
         (only-in "tools.rkt" run-freezer))

(provide reify-file
         facts->program
         facts->database)

(define-runtime-path stdlib-dir "../lib")
(define-runtime-path schema-file "../analysis/schema.slog")

;; path [sources: path -> text] -> the facts, each "(rel arg ...)"
(define (reify-file path #:sources [sources (hash)])
  (define main (path->string (path->complete-path path)))
  (define override
    (and (positive? (hash-count sources))
         (for/hash ([(file text) (in-hash sources)])
           (values (source-key file) text))))
  (define out (open-output-string))
  (parameterize ([parse-errors-raise? #t]
                 [current-source-override override])
    (reify-program main out))
  (string-split (get-output-string out) "\n"))

(define (facts->program facts)
  (string-append*
   ";; Generated by compiler/reify.rkt; the schema is analysis/schema.slog\n"
   (for/list ([f (in-list facts)]) (string-append "rule " f "\n"))))

;; Write the facts as the database data/NAME, replacing any there.  The
;; freezer's stream first declares each table and constructor, with the
;; arities the schema gives them.
(define (facts->database facts name)
  (define dir (path->complete-path (build-path "data" name)))
  (when (directory-exists? dir) (delete-directory/files dir))
  (make-directory* (build-path "data"))
  (run-freezer (path->string dir)
               (string-append (string-join (schema-declarations) "\n") "\n"
                              (string-join facts "\n") "\n")))

(define (schema-declarations)
  (match-define `(module ,_ ,_ ,ast) (parse-file (path->string schema-file)))
  (let walk ([ast ast])
    (match ast
      [`(syn ,_ table (syn ,_ ,name . ,columns) ,more)
       (cons (format "(table ~a ~a)" name (length columns)) (walk more))]
      [`(syn ,_ struct (syn ,_ ,name . ,fields) ,more)
       (cons (format "(struct ~a ~a)" name (length fields)) (walk more))]
      [`(syn ,_ union (syn ,_ ,_ . ,arms) ,more)
       (append (for/list ([arm (in-list arms)])
                 (match-define `(syn ,_ ,name . ,fields) arm)
                 (format "(struct ~a ~a)" name (length fields)))
               (walk more))]
      [`(syn ,_ top-level) '()]
      [_ (walk (last ast))])))

;; -----------------------------------------------------------------------
;; Output: one fact a line.

(define (str s)
  (define text (if (string? s) s (format "~a" s)))
  (string-append "\"" (regexp-replace* #rx"[\\\\\"]" text "\\\\&") "\""))

(define (slog-list items) (string-append "[" (string-join items " ") "]"))

(define (emit out rel . args)
  (fprintf out "(~a ~a)\n" rel (string-join args " ")))

;; -----------------------------------------------------------------------
;; Positions.  Parsed nodes carry the tokens they start and end at; a bare
;; symbol (a variable, or a name in a declaration) carries none, so it is
;; found among its parent's tokens, reading left to right.

(struct source (file tokens index))   ; file: its number; tokens: the real ones

(define (real-tokens raw)
  (for/vector ([t (in-list raw)]
               #:unless (or (eof-object? (first t))
                            (<= (length t) 1)
                            (memq (second t) '(space comment newline eof))))
    t))

(define (make-source file raw)
  (define tokens (real-tokens raw))
  (source file tokens (for/hasheq ([t (in-vector tokens)] [i (in-naturals)]) (values t i))))

(define (token-loc src t)
  (define pos (token->pos t))
  (format "(loc ~a ~a ~a)" (source-file src)
          (add1 (pos->startline pos)) (add1 (pos->startcol pos))))

(define (span src node)
  (match node
    [`(syn (prov ,l ,r) . ,_)
     (values (hash-ref (source-index src) l #f) (hash-ref (source-index src) r #f))]
    [_ (values #f #f)]))

;; Where a node is: at the name of a prefix form `(name ...)`, else its
;; first token.
(define (node-loc src node)
  (define-values (l _r) (span src node))
  (define tokens (source-tokens src))
  (define head (and l (pair? (cddr node)) (caddr node)))
  (cond
    [(not l) (format "(loc ~a 0 0)" (source-file src))]   ; a bare name: no tokens of its own
    [(and (symbol? head)
          (eq? 'popen (token->tag (vector-ref tokens l)))
          (< (add1 l) (vector-length tokens))
          (equal? (symbol->string head) (token->str (vector-ref tokens (add1 l)))))
     (token-loc src (vector-ref tokens (add1 l)))]
    [else (token-loc src (vector-ref tokens l))]))

;; The positions of a node's arguments (all but its head), in order.
(define (argument-locs src node)
  (match-define `(syn ,_ ,head . ,args) node)
  (define-values (l r) (span src node))
  (define tokens (source-tokens src))
  (define here (node-loc src node))
  (define start
    (if (and l (eq? 'popen (token->tag (vector-ref tokens l)))) (+ l 2) (or l 0)))
  (let loop ([args args] [cursor start] [out '()])
    (match args
      ['() (reverse out)]
      [(cons (? pair? arg) more)
       (define-values (_l end) (span src arg))
       (loop more (if end (add1 end) cursor) (cons (node-loc src arg) out))]
      [(cons (? symbol? name) more)
       (define found
         (and r (for/first ([i (in-range cursor (add1 r))]
                            #:when (equal? (symbol->string name)
                                           (token->str (vector-ref tokens i))))
                  i)))
       (if found
           (loop more (add1 found) (cons (token-loc src (vector-ref tokens found)) out))
           (loop more cursor (cons here out)))]
      [(cons _ more) (loop more cursor (cons here out))])))

;; -----------------------------------------------------------------------
;; Terms.

(define (unparse ast)
  (match ast
    [`(syn ,_ const ,v) (if (string? v) (format "\"~a\"" v) (format "~a" v))]
    [`(syn ,_ ,(? (lambda (h) (equal? h '|[]|))) . ,args)
     (format "[~a]" (string-join (map unparse args) " "))]
    [`(syn ,_ . ,parts) (format "(~a)" (string-join (map unparse parts) " "))]
    [_ (format "~a" ast)]))

(define (term src ast loc)
  (match ast
    ['_ (format "(wild ~a)" loc)]
    [(? symbol? x) (format "(var ~a ~a)" (str x) loc)]
    [`(syn ,_ const ,(? exact-integer? n)) (format "(int_lit ~a ~a)" n loc)]
    [`(syn ,_ const ,(? real? x)) (format "(float_lit ~a ~a)" x loc)]
    ;; the parser keeps a string's text as written, escapes and all
    [`(syn ,_ const ,(? string? s)) (format "(str_lit \"~a\" ~a)" s loc)]
    [`(syn ,_ const ,(? symbol? b)) (format "(bool_lit ~a ~a)" (str b) loc)]
    [`(syn ,_ lambda (syn ,_ ,(? symbol? params) ...) ,body)
     (format "(lam ~a ~a)" (slog-list (map str params))
             (term src body (node-loc src ast)))]
    [`(syn ,_ ,(? symbol? head) . ,args)
     (define ts (map (lambda (a l) (term src a l)) args (argument-locs src ast)))
     (case head
       [(|[]|) (format "(lst ~a)" (slog-list ts))]
       [(...) (format "(splice ~a)" (first ts))]
       [else (format "(call ~a ~a ~a)" (str head) (slog-list ts) (node-loc src ast))])]
    [_ (format "(other ~a ~a)" (str (unparse ast)) loc)]))

(define (arguments src ast)
  (slog-list (map (lambda (a l) (term src a l)) (cdddr ast) (argument-locs src ast))))

;; -----------------------------------------------------------------------
;; Rules.  A body's alternatives (`|`, and parenthesized groups) are
;; multiplied out, each alternative becoming a rule of its own at the same
;; location, as the compiler's desugaring does.

(define guards '(< <= > >= /=))

(define (disjuncts clause)
  (match clause
    [`(syn ,_ \| . ,alts) (append-map disjuncts alts)]
    [`(syn ,_ ,(? pair? first) . ,more) (alternatives (cons first more))]
    [_ (list (list clause))]))

(define (alternatives clauses)
  (for/fold ([alts '(())]) ([c (in-list clauses)])
    (for*/list ([a (in-list alts)] [d (in-list (disjuncts c))]) (append a d))))

(define (reify-rule src out next-id form heads body)
  (for ([alt (in-list (alternatives body))])
    (define id (next-id))
    (define (at node) (node-loc src node))
    (emit out "rule_at" (~a id) (~a (length alt)) (at form))
    (for ([h (in-list heads)] [i (in-naturals)])
      (match h
        [`(syn ,_ ,(? symbol? rel) . ,_)
         (emit out "head" (~a id) (~a i) (str rel) (arguments src h) (at h))]
        [_ (emit out "clause_other" (~a id) (~a i) (str (unparse h)) (at h))]))
    (for ([c (in-list alt)] [i (in-naturals)])
      (match c
        [`(syn ,_ ~ ,(and atom `(syn ,_ ,(? symbol? rel) . ,_)))
         (emit out "negated" (~a id) (~a i) (str rel) (arguments src atom) (at atom))]
        [`(syn ,_ = ,a ,b)
         (match-define (list la lb) (argument-locs src c))
         (emit out "binds" (~a id) (~a i) (term src a la) (term src b lb) (at c))]
        [`(syn ,_ ,(? (lambda (op) (memq op guards)) op) ,a ,b)
         (match-define (list la lb) (argument-locs src c))
         (emit out "guard" (~a id) (~a i) (str op) (term src a la) (term src b lb) (at c))]
        [`(syn ,_ ,(? symbol? rel) . ,_)
         (emit out "body" (~a id) (~a i) (str rel) (arguments src c) (at c))]
        [_ (emit out "clause_other" (~a id) (~a i) (str (unparse c)) (at c))]))))

;; -----------------------------------------------------------------------
;; Declarations.

(define (type-text t) (unparse t))

;; A type as written in a column or field.  An inline declaration --
;; `(kaddr expr)` declares the struct kaddr, `(halt)` the constant halt --
;; is declared where it stands, and names the type, as modules.rkt
;; flattens it.
(define type-formers '(list map set |[]| union min max flat count))

(define (reify-type src out t)
  (match t
    [`(syn ,_ ,(? symbol? name) . ,fields)
     #:when (not (memq name type-formers))
     (reify-constructor src out name fields t)
     (symbol->string name)]
    ;; an inline lattice, `(min int)`: a lattice type named by its text
    [`(syn ,_ ,(or 'min 'max 'flat 'count 'set) . ,_)
     (define text (type-text t))
     (emit out "type_decl" (str text) (str "lattice") (node-loc src t))
     (emit out "lattice_spec" (str text) (str text))
     text]
    [_ (type-text t)]))

;; a union arm: a type it includes, or a constructor declared in place
(define (reify-member src out owner arm)
  (emit out "union_member" (str owner)
        (str (if (symbol? arm) arm (reify-type src out arm)))))

(define (reify-constructor src out name fields node)
  (emit out "constructor" (str name) (~a (length fields)) (node-loc src node))
  (for ([f (in-list fields)] [i (in-naturals)])
    (emit out "field" (str name) (~a i) (str (reify-type src out f)))))

(define (reify-columns src out name types)
  (for ([t (in-list types)] [i (in-naturals)])
    (emit out "column" (str name) (~a i) (str (reify-type src out t)))))

;; -----------------------------------------------------------------------
;; Files.

(define (library-file? path)
  (and (directory-exists? stdlib-dir)
       (string-prefix? path (path->string (path->directory-path (simplify-path stdlib-dir))))))

(define (reify-program main out)
  (define seen (mutable-set))
  ;; files are numbered as they are first named
  (define numbers (make-hash))
  (define (number file)
    (hash-ref! numbers file (lambda () (add1 (hash-count numbers)))))
  (define rule-count 0)
  (define (next-id) (set! rule-count (add1 rule-count)) rule-count)
  (emit out "main_file" (~a (number main)))
  (for ([p (in-list (sort (hash-keys prim-fun-env) symbol<?))])
    (emit out "primitive" (str p)))
  (let visit ([file main])
    (unless (set-member? seen file)
      (set-add! seen file)
      (match-define `(module ,_ ,raw ,ast) (parse-file file))
      (define src (make-source (number file) raw))
      (define-values (dir _name _dir?) (split-path file))
      (emit out "source_file" (~a (number file)) (str file))
      (when (library-file? file) (emit out "library_file" (~a (number file))))
      (let form ([ast ast])
        (define (next) (form (last ast)))
        (define (at node) (node-loc src node))
        (match ast
          [`(syn ,_ top-level) (void)]
          [`(syn ,_ include (syn ,_ const ,(? string? target)) ,_)
           (define resolved (resolve-include target dir))
           (emit out "includes" (~a (number file)) (~a (number resolved)) (at ast))
           (if (or (file-exists? resolved)
                   (let ([ov (current-source-override)])
                     (and ov (hash-has-key? ov (source-key resolved)))))
               (visit resolved)
               (emit out "missing_include" (~a (number file)) (str target) (at ast)))
           (next)]
          [`(syn ,_ ,(and kind (or 'run 'instantiate)) (syn ,_ const ,(? string? target)) . ,_)
           (emit out "loads" (~a (number file)) (str kind) (str target) (at ast))
           (next)]
          [`(syn ,_ ,(and kind (or 'table 'struct)) (syn ,_ ,(? symbol? name) . ,types) ,_)
           (define decl (cadddr ast))
           (if (eq? kind 'table)
               (begin (emit out "relation" (str name) (str "table") (~a (length types)) (at decl))
                      (reify-columns src out name types))
               (begin (emit out "type_decl" (str name) (str "struct") (at decl))
                      (reify-constructor src out name types decl)))
           (next)]
          [`(syn ,_ ,(and kind (or 'demand 'extern)) . ,parts)
           (define sig (if (eq? kind 'extern) (cadr parts) (car parts)))
           (define answers (drop-right (if (eq? kind 'extern) (cddr parts) (cdr parts)) 1))
           (match sig
             [`(syn ,_ ,(? symbol? name) . ,inputs)
              (emit out "relation" (str name) (str kind)
                    (~a (+ (length inputs) (length answers))) (at sig))
              (emit out "demand_inputs" (str name) (~a (length inputs)))
              (reify-columns src out name (append inputs answers))]
             [_ (void)])
           (next)]
          [`(syn ,_ union (syn ,_ ,(? symbol? name) . ,arms) ,_)
           (emit out "type_decl" (str name) (str "union") (at (cadddr ast)))
           (for ([arm (in-list arms)]) (reify-member src out name arm))
           (next)]
          [`(syn ,_ enum (syn ,_ ,(? symbol? name) . ,members) ,_)
           (define decl (cadddr ast))
           (cond
             [(null? members) (reify-constructor src out name '() decl)]
             [else
              (emit out "type_decl" (str name) (str "enum") (at decl))
              (for ([m (in-list members)] [l (in-list (argument-locs src decl))]
                    #:when (symbol? m))
                (emit out "constructor" (str m) "0" l)
                (emit out "union_member" (str name) (str m)))])
           (next)]
          [`(syn ,_ lattice (syn ,_ ,(? symbol? name) ,spec) ,_)
           (emit out "type_decl" (str name) (str "lattice") (at (cadddr ast)))
           (emit out "lattice_spec" (str name) (str (type-text spec)))
           (next)]
          [`(syn ,_ rule ,clauses ... ,(and arrow (or '--> '<--)) ,more ... ,_)
           (define-values (body heads)
             (if (eq? arrow '-->) (values clauses more) (values more clauses)))
           (reify-rule src out next-id ast heads body)
           (next)]
          [`(syn ,_ . ,_) (next)]
          [_ (void)])))))

;; -----------------------------------------------------------------------

(define (serve)
  (let loop ()
    (define line (read-line))
    (unless (eof-object? line)
      (define start (current-inexact-milliseconds))
      (define request (with-handlers ([exn:fail? (lambda (_) (hasheq))]) (string->jsexpr line)))
      (define answer
        (with-handlers ([exn:fail? (lambda (e) (hasheq 'ok #f 'error (exn-message e)))])
          (define sources
            (for/hash ([(file text) (in-hash (hash-ref request 'sources (hasheq)))])
              (values (symbol->string file) text)))
          (define facts (reify-file (hash-ref request 'path) #:sources sources))
          (when (hash-ref request 'freeze #f)
            (facts->database facts (hash-ref request 'freeze)))
          ;; "program": also write the facts as a Slog program there
          (when (hash-ref request 'program #f)
            (call-with-output-file (hash-ref request 'program) #:exists 'truncate
              (lambda (port) (write-string (facts->program facts) port))))
          (hasheq 'ok #t 'facts (length facts))))
      (write-json (hash-set* answer
                             'id (hash-ref request 'id 0)
                             'ms (inexact->exact (round (- (current-inexact-milliseconds) start)))))
      (newline)
      (flush-output)
      (loop))))

(module+ main
  (define serve? #f)
  (define freeze #f)
  (command-line
   #:program "reify"
   #:once-each
   [("--serve") "Answer JSON requests, one a line, on stdin" (set! serve? #t)]
   [("--freeze") name "Write the facts as the database data/NAME" (set! freeze name)]
   #:args files
   (cond
     [serve? (serve)]
     [else
      (for ([file (in-list files)])
        (define facts (reify-file file))
        (if freeze
            (facts->database facts freeze)
            (write-string (facts->program facts))))])))
